version: "3"

networks:
  near-sffl-aggregator:
    driver: bridge

services:
  near-sffl-aggregator:
    image: ghcr.io/nuffle-labs/near-sffl/aggregator:${SFFL_RELEASE}
    container_name: near-sffl-aggregator
    volumes:
      - ./:/near-sffl/
    networks:
      - near-sffl-aggregator
    working_dir: /near-sffl
    command: 
      - --config 
      - config/aggregator.yaml
      - --sffl-deployment 
      - config/deployment/17000.json
      - --ecdsa-private-key 
      - ${ECDSA_PRIVATE_KEY}
    restart: unless-stopped
    ports:
      - "4001:4001"
      - "4002:4002"
      - "127.0.0.1:9091:9091"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "50"
        compress: "true"

  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana:9.4.1
    container_name: grafana
    volumes:
      - grafana_data_aggregator:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning
    networks:
      - near-sffl-aggregator
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"

  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data_aggregator:/prometheus
    networks:
      - near-sffl-aggregator
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
      - --web.enable-remote-write-receiver
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data_aggregator:
  grafana_data_aggregator: