version: "3"

networks:
  near-sffl-relayer:
    driver: bridge

services:
  relayer_421614:
    image: ghcr.io/nuffle-labs/near-sffl/relayer:${SFFL_RELEASE}
    container_name: near-sffl-relayer-421614
    volumes:
      - ${NEAR_KEYS_DIR}:/root/.near-credentials
    networks:
      - near-sffl-relayer
    expose:
      - 9091
    command:
      - run-args
      - --rpc-url
      - wss://arbitrum-sepolia-rpc.publicnode.com
      - --da-account-id
      - sfrelayer421614-1.testnet
      - --key-path
      - /root/.near-credentials/${NEAR_CHAIN_ID}/sfrelayer421614-1.testnet.json
      - --network
      - ${NEAR_RPC_URL}
      - --metrics-ip-port-address
      - near-sffl-relayer-421614:9091
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "20"
        compress: "true"

  relayer_11155420:
    image: ghcr.io/nuffle-labs/near-sffl/relayer:${SFFL_RELEASE}
    container_name: near-sffl-relayer-11155420
    volumes:
      - ${NEAR_KEYS_DIR}:/root/.near-credentials
    networks:
      - near-sffl-relayer
    expose:
      - 9091
    command:
      - run-args
      - --rpc-url
      - wss://optimism-sepolia-rpc.publicnode.com
      - --da-account-id
      - sfrelayer11155420-1.testnet
      - --key-path
      - /root/.near-credentials/${NEAR_CHAIN_ID}/sfrelayer11155420-1.testnet.json
      - --network
      - ${NEAR_RPC_URL}
      - --metrics-ip-port-address
      - near-sffl-relayer-11155420:9091
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "20"
        compress: "true"

  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana:9.4.1
    container_name: grafana
    volumes:
      - grafana_data_relayer:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning
    networks:
      - near-sffl-relayer
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"

  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data_relayer:/prometheus
    networks:
      - near-sffl-relayer
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
      - --web.enable-remote-write-receiver
    restart: unless-stopped
    ports:
      - "127.0.0.1:9091:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data_relayer:
